name: Default
description: File a bug report etc.
title: ""

body:
  - type: markdown
    attributes:
      value: |
        Please do the items from the checklist below. I may close your issue without further comments if it's blatant that you didn't. Please let's respect each other's time.

  - type: checkboxes
    id: latest
    attributes:
      label: "Checklist"
      options:
        - label: I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
          required: true
        - label: I have read the entirety of the FAQ section in the readme, and my question was not answered there, or was not answered sufficiently
          required: true
        - label: I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the FAQ, and they didn't help
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Your issue
      value: ""
    validations:
      required: true
